"""initial_decarbx_schema

Revision ID: f381afcf2279
Revises: 
Create Date: 2026-09-03 14:17:55.511789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f381afcf2279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_data',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reporting_period', sa.String(length=20), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=20), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_data_anomaly_flag'), 'activity_data', ['anomaly_flag'], unique=False)
    op.create_index(op.f('ix_activity_data_category'), 'activity_data', ['category'], unique=False)
    op.create_index(op.f('ix_activity_data_entity_id'), 'activity_data', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_data_facility_id'), 'activity_data', ['facility_id'], unique=False)
    op.create_index(op.f('ix_activity_data_is_deleted'), 'activity_data', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_activity_data_organization_id'), 'activity_data', ['organization_id'], unique=False)
    op.create_index(op.f('ix_activity_data_scope'), 'activity_data', ['scope'], unique=False)
    op.create_table('allocations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('allocation_method', sa.String(length=50), nullable=False),
    sa.Column('allocation_percentage', sa.Float(), nullable=False),
    sa.Column('target_facility_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_is_deleted'), 'allocations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_allocations_organization_id'), 'allocations', ['organization_id'], unique=False)
    op.create_table('anomaly_records',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('activity_data_id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('deviation_pct', sa.Float(), nullable=False),
    sa.Column('rule_triggered', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_records_activity_data_id'), 'anomaly_records', ['activity_data_id'], unique=False)
    op.create_index(op.f('ix_anomaly_records_is_deleted'), 'anomaly_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_anomaly_records_organization_id'), 'anomaly_records', ['organization_id'], unique=False)
    op.create_table('baselines',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('scope1_tco2e', sa.Float(), nullable=False),
    sa.Column('scope2_location_tco2e', sa.Float(), nullable=False),
    sa.Column('scope2_market_tco2e', sa.Float(), nullable=False),
    sa.Column('scope3_tco2e', sa.Float(), nullable=False),
    sa.Column('total_tco2e', sa.Float(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('restatement_reason', sa.Text(), nullable=True),
    sa.Column('restated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_is_deleted'), 'baselines', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_baselines_organization_id'), 'baselines', ['organization_id'], unique=False)
    op.create_table('cbam_records',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_description', sa.String(length=255), nullable=False),
    sa.Column('country_of_origin', sa.String(length=100), nullable=False),
    sa.Column('reporting_quarter', sa.String(length=20), nullable=False),
    sa.Column('imported_volume_tonnes', sa.Float(), nullable=False),
    sa.Column('direct_embedded_emissions', sa.Float(), nullable=False),
    sa.Column('indirect_embedded_emissions', sa.Float(), nullable=False),
    sa.Column('total_embedded_emissions_tco2e', sa.Float(), nullable=False),
    sa.Column('carbon_price_due_eur', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cbam_records_is_deleted'), 'cbam_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_cbam_records_organization_id'), 'cbam_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cbam_records_product_code'), 'cbam_records', ['product_code'], unique=False)
    op.create_table('connector_configs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_frequency', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_configs_is_deleted'), 'connector_configs', ['is_deleted'], unique=False)
    op.create_table('credit_offsets',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('registry', sa.String(length=50), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('quantity_tco2e', sa.Float(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('retirement_status', sa.String(length=30), nullable=False),
    sa.Column('retirement_beneficiary', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_credit_offsets_is_deleted'), 'credit_offsets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_credit_offsets_organization_id'), 'credit_offsets', ['organization_id'], unique=False)
    op.create_table('emission_factors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('gas_type', sa.String(length=50), nullable=False),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('unit_numerator', sa.String(length=20), nullable=False),
    sa.Column('unit_denominator', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uncertainty_pct', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_category'), 'emission_factors', ['category'], unique=False)
    op.create_index(op.f('ix_emission_factors_is_deleted'), 'emission_factors', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emission_factors_version'), 'emission_factors', ['version'], unique=False)
    op.create_table('evidence',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_kb', sa.Float(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('linked_data_points', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_is_deleted'), 'evidence', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_table('frameworks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frameworks_code'), 'frameworks', ['code'], unique=True)
    op.create_index(op.f('ix_frameworks_is_deleted'), 'frameworks', ['is_deleted'], unique=False)
    op.create_table('import_batches',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('errors_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_is_deleted'), 'import_batches', ['is_deleted'], unique=False)
    op.create_table('intensity_metrics',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('revenue_m_usd', sa.Float(), nullable=True),
    sa.Column('fte_employees', sa.Integer(), nullable=True),
    sa.Column('production_volume_tons', sa.Float(), nullable=True),
    sa.Column('scope1_2_intensity_rev', sa.Float(), nullable=True),
    sa.Column('total_intensity_fte', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intensity_metrics_is_deleted'), 'intensity_metrics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_intensity_metrics_organization_id'), 'intensity_metrics', ['organization_id'], unique=False)
    op.create_table('materials',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('default_emission_factor_id', sa.String(length=36), nullable=True),
    sa.Column('recycled_content_pct', sa.Float(), nullable=False),
    sa.Column('density_kg_m3', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_is_deleted'), 'materials', ['is_deleted'], unique=False)
    op.create_table('meter_readings',
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('meter_identifier', sa.String(length=100), nullable=False),
    sa.Column('meter_type', sa.String(length=50), nullable=False),
    sa.Column('reading_value', sa.Float(), nullable=False),
    sa.Column('reading_unit', sa.String(length=50), nullable=False),
    sa.Column('reading_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_facility_id'), 'meter_readings', ['facility_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_is_deleted'), 'meter_readings', ['is_deleted'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('reporting_currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('functional_unit', sa.String(length=100), nullable=False),
    sa.Column('unit_weight_kg', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('questionnaires',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('materiality_category', sa.String(length=100), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_is_deleted'), 'questionnaires', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_questionnaires_organization_id'), 'questionnaires', ['organization_id'], unique=False)
    op.create_table('reduction_initiatives',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lever_type', sa.String(length=100), nullable=False),
    sa.Column('target_reduction_tco2e', sa.Float(), nullable=False),
    sa.Column('actual_reduction_tco2e', sa.Float(), nullable=False),
    sa.Column('capex_usd', sa.Float(), nullable=False),
    sa.Column('opex_annual_usd', sa.Float(), nullable=False),
    sa.Column('payback_years', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reduction_initiatives_is_deleted'), 'reduction_initiatives', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_reduction_initiatives_organization_id'), 'reduction_initiatives', ['organization_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('baseline_year', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('levers', sa.JSON(), nullable=False),
    sa.Column('projected_reduction_tco2e', sa.Float(), nullable=False),
    sa.Column('projected_reduction_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_is_deleted'), 'scenarios', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_scenarios_organization_id'), 'scenarios', ['organization_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('onboarding_status', sa.String(length=30), nullable=False),
    sa.Column('spend_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index(op.f('ix_suppliers_is_deleted'), 'suppliers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_table('targets',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('scope_coverage', sa.String(length=50), nullable=False),
    sa.Column('baseline_year', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('target_reduction_pct', sa.Float(), nullable=False),
    sa.Column('current_progress_pct', sa.Float(), nullable=False),
    sa.Column('trajectory_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_is_deleted'), 'targets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_targets_organization_id'), 'targets', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('facility_permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_preview', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_is_deleted'), 'webhook_logs', ['is_deleted'], unique=False)
    op.create_table('action_plans',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('initiative_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_reduction_tco2e', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plans_is_deleted'), 'action_plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_action_plans_supplier_id'), 'action_plans', ['supplier_id'], unique=False)
    op.create_table('assurance_requests',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('framework_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('auditor_firm', sa.String(length=255), nullable=False),
    sa.Column('auditor_name', sa.String(length=255), nullable=False),
    sa.Column('assurance_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('signoff_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assurance_requests_is_deleted'), 'assurance_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assurance_requests_organization_id'), 'assurance_requests', ['organization_id'], unique=False)
    op.create_table('boms',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('scrap_rate_pct', sa.Float(), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('parent_component_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boms_is_deleted'), 'boms', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_boms_product_id'), 'boms', ['product_id'], unique=False)
    op.create_table('calculations',
    sa.Column('activity_data_id', sa.String(length=36), nullable=False),
    sa.Column('factor_id', sa.String(length=36), nullable=False),
    sa.Column('factor_version', sa.String(length=20), nullable=False),
    sa.Column('formula_applied', sa.Text(), nullable=False),
    sa.Column('unit_conversion_factor', sa.Float(), nullable=False),
    sa.Column('allocation_pct', sa.Float(), nullable=False),
    sa.Column('emissions_tco2e', sa.Float(), nullable=False),
    sa.Column('uncertainty_min_tco2e', sa.Float(), nullable=False),
    sa.Column('uncertainty_max_tco2e', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_data_id'], ['activity_data.id'], ),
    sa.ForeignKeyConstraint(['factor_id'], ['emission_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculations_activity_data_id'), 'calculations', ['activity_data_id'], unique=False)
    op.create_index(op.f('ix_calculations_is_deleted'), 'calculations', ['is_deleted'], unique=False)
    op.create_table('data_points',
    sa.Column('framework_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('reported_value', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('calculation_link', sa.String(length=255), nullable=True),
    sa.Column('evidence_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_points_code'), 'data_points', ['code'], unique=False)
    op.create_index(op.f('ix_data_points_framework_id'), 'data_points', ['framework_id'], unique=False)
    op.create_index(op.f('ix_data_points_is_deleted'), 'data_points', ['is_deleted'], unique=False)
    op.create_table('disclosures',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('framework_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disclosures_framework_id'), 'disclosures', ['framework_id'], unique=False)
    op.create_index(op.f('ix_disclosures_is_deleted'), 'disclosures', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_disclosures_organization_id'), 'disclosures', ['organization_id'], unique=False)
    op.create_table('emission_records',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('activity_data_id', sa.String(length=36), nullable=False),
    sa.Column('emission_factor_id', sa.String(length=36), nullable=False),
    sa.Column('factor_version', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('reporting_period', sa.String(length=20), nullable=False),
    sa.Column('gross_emissions_tco2e', sa.Float(), nullable=False),
    sa.Column('net_emissions_tco2e', sa.Float(), nullable=False),
    sa.Column('rec_offset_tco2e', sa.Float(), nullable=False),
    sa.Column('formula_string', sa.Text(), nullable=False),
    sa.Column('unit_conversions_applied', sa.String(length=255), nullable=False),
    sa.Column('allocation_method', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_scenario', sa.Boolean(), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_data_id'], ['activity_data.id'], ),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_records_activity_data_id'), 'emission_records', ['activity_data_id'], unique=False)
    op.create_index(op.f('ix_emission_records_category'), 'emission_records', ['category'], unique=False)
    op.create_index(op.f('ix_emission_records_entity_id'), 'emission_records', ['entity_id'], unique=False)
    op.create_index(op.f('ix_emission_records_facility_id'), 'emission_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_emission_records_is_deleted'), 'emission_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emission_records_is_scenario'), 'emission_records', ['is_scenario'], unique=False)
    op.create_index(op.f('ix_emission_records_organization_id'), 'emission_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_emission_records_reporting_period'), 'emission_records', ['reporting_period'], unique=False)
    op.create_index(op.f('ix_emission_records_scenario_id'), 'emission_records', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_emission_records_scope'), 'emission_records', ['scope'], unique=False)
    op.create_table('entities',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('consolidation_method', sa.String(length=50), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_code'), 'entities', ['code'], unique=False)
    op.create_index(op.f('ix_entities_is_deleted'), 'entities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_entities_organization_id'), 'entities', ['organization_id'], unique=False)
    op.create_table('packagings',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('packaging_type', sa.String(length=100), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('recyclability_pct', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packagings_is_deleted'), 'packagings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_packagings_product_id'), 'packagings', ['product_id'], unique=False)
    op.create_table('pcf_records',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('boundary', sa.String(length=50), nullable=False),
    sa.Column('functional_unit', sa.String(length=100), nullable=False),
    sa.Column('allocation_method', sa.String(length=50), nullable=False),
    sa.Column('total_pcf_kgco2e', sa.Float(), nullable=False),
    sa.Column('stage_breakdown', sa.JSON(), nullable=False),
    sa.Column('iso_14067_compliant', sa.Boolean(), nullable=False),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcf_records_is_deleted'), 'pcf_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pcf_records_product_id'), 'pcf_records', ['product_id'], unique=False)
    op.create_table('processes',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('process_name', sa.String(length=255), nullable=False),
    sa.Column('electricity_kwh', sa.Float(), nullable=False),
    sa.Column('thermal_energy_mj', sa.Float(), nullable=False),
    sa.Column('direct_emissions_kgco2e', sa.Float(), nullable=False),
    sa.Column('scrap_loss_pct', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_is_deleted'), 'processes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_processes_product_id'), 'processes', ['product_id'], unique=False)
    op.create_table('questionnaire_submissions',
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('attestation_name', sa.String(length=255), nullable=True),
    sa.Column('attestation_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_submissions_is_deleted'), 'questionnaire_submissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_questionnaire_submissions_questionnaire_id'), 'questionnaire_submissions', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_submissions_supplier_id'), 'questionnaire_submissions', ['supplier_id'], unique=False)
    op.create_table('routes',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_is_deleted'), 'routes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_routes_product_id'), 'routes', ['product_id'], unique=False)
    op.create_table('scorecards',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('emissions_scope1_2_tco2e', sa.Float(), nullable=False),
    sa.Column('emissions_intensity', sa.Float(), nullable=True),
    sa.Column('maturity_score', sa.Float(), nullable=False),
    sa.Column('rating', sa.String(length=5), nullable=False),
    sa.Column('yoy_change_pct', sa.Float(), nullable=False),
    sa.Column('cdp_score', sa.String(length=10), nullable=True),
    sa.Column('sbti_committed', sa.Boolean(), nullable=False),
    sa.Column('renewable_energy_pct', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorecards_is_deleted'), 'scorecards', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_scorecards_supplier_id'), 'scorecards', ['supplier_id'], unique=False)
    op.create_table('facilities',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('grid_region', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_code'), 'facilities', ['code'], unique=False)
    op.create_index(op.f('ix_facilities_entity_id'), 'facilities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_facilities_is_deleted'), 'facilities', ['is_deleted'], unique=False)
    op.create_table('reporting_boundaries',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('boundary_type', sa.String(length=50), nullable=False),
    sa.Column('consolidation_approach', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporting_boundaries_entity_id'), 'reporting_boundaries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reporting_boundaries_is_deleted'), 'reporting_boundaries', ['is_deleted'], unique=False)
    op.create_table('departments',
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_facility_id'), 'departments', ['facility_id'], unique=False)
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.create_table('cost_centers',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('budget_currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_centers_code'), 'cost_centers', ['code'], unique=False)
    op.create_index(op.f('ix_cost_centers_department_id'), 'cost_centers', ['department_id'], unique=False)
    op.create_index(op.f('ix_cost_centers_is_deleted'), 'cost_centers', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_centers_is_deleted'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_department_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_code'), table_name='cost_centers')
    op.drop_table('cost_centers')
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_index(op.f('ix_departments_facility_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_reporting_boundaries_is_deleted'), table_name='reporting_boundaries')
    op.drop_index(op.f('ix_reporting_boundaries_entity_id'), table_name='reporting_boundaries')
    op.drop_table('reporting_boundaries')
    op.drop_index(op.f('ix_facilities_is_deleted'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_entity_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_code'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_scorecards_supplier_id'), table_name='scorecards')
    op.drop_index(op.f('ix_scorecards_is_deleted'), table_name='scorecards')
    op.drop_table('scorecards')
    op.drop_index(op.f('ix_routes_product_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_is_deleted'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_questionnaire_submissions_supplier_id'), table_name='questionnaire_submissions')
    op.drop_index(op.f('ix_questionnaire_submissions_questionnaire_id'), table_name='questionnaire_submissions')
    op.drop_index(op.f('ix_questionnaire_submissions_is_deleted'), table_name='questionnaire_submissions')
    op.drop_table('questionnaire_submissions')
    op.drop_index(op.f('ix_processes_product_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_is_deleted'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_pcf_records_product_id'), table_name='pcf_records')
    op.drop_index(op.f('ix_pcf_records_is_deleted'), table_name='pcf_records')
    op.drop_table('pcf_records')
    op.drop_index(op.f('ix_packagings_product_id'), table_name='packagings')
    op.drop_index(op.f('ix_packagings_is_deleted'), table_name='packagings')
    op.drop_table('packagings')
    op.drop_index(op.f('ix_entities_organization_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_is_deleted'), table_name='entities')
    op.drop_index(op.f('ix_entities_code'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_emission_records_scope'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_scenario_id'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_reporting_period'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_organization_id'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_is_scenario'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_is_deleted'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_facility_id'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_entity_id'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_category'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_activity_data_id'), table_name='emission_records')
    op.drop_table('emission_records')
    op.drop_index(op.f('ix_disclosures_organization_id'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_is_deleted'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_framework_id'), table_name='disclosures')
    op.drop_table('disclosures')
    op.drop_index(op.f('ix_data_points_is_deleted'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_framework_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_code'), table_name='data_points')
    op.drop_table('data_points')
    op.drop_index(op.f('ix_calculations_is_deleted'), table_name='calculations')
    op.drop_index(op.f('ix_calculations_activity_data_id'), table_name='calculations')
    op.drop_table('calculations')
    op.drop_index(op.f('ix_boms_product_id'), table_name='boms')
    op.drop_index(op.f('ix_boms_is_deleted'), table_name='boms')
    op.drop_table('boms')
    op.drop_index(op.f('ix_assurance_requests_organization_id'), table_name='assurance_requests')
    op.drop_index(op.f('ix_assurance_requests_is_deleted'), table_name='assurance_requests')
    op.drop_table('assurance_requests')
    op.drop_index(op.f('ix_action_plans_supplier_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_is_deleted'), table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_webhook_logs_is_deleted'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_targets_organization_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_is_deleted'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_deleted'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_scenarios_organization_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_is_deleted'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_reduction_initiatives_organization_id'), table_name='reduction_initiatives')
    op.drop_index(op.f('ix_reduction_initiatives_is_deleted'), table_name='reduction_initiatives')
    op.drop_table('reduction_initiatives')
    op.drop_index(op.f('ix_questionnaires_organization_id'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_is_deleted'), table_name='questionnaires')
    op.drop_table('questionnaires')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_meter_readings_is_deleted'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_facility_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_materials_is_deleted'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_intensity_metrics_organization_id'), table_name='intensity_metrics')
    op.drop_index(op.f('ix_intensity_metrics_is_deleted'), table_name='intensity_metrics')
    op.drop_table('intensity_metrics')
    op.drop_index(op.f('ix_import_batches_is_deleted'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_frameworks_is_deleted'), table_name='frameworks')
    op.drop_index(op.f('ix_frameworks_code'), table_name='frameworks')
    op.drop_table('frameworks')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_is_deleted'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_emission_factors_version'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_is_deleted'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_category'), table_name='emission_factors')
    op.drop_table('emission_factors')
    op.drop_index(op.f('ix_credit_offsets_organization_id'), table_name='credit_offsets')
    op.drop_index(op.f('ix_credit_offsets_is_deleted'), table_name='credit_offsets')
    op.drop_table('credit_offsets')
    op.drop_index(op.f('ix_connector_configs_is_deleted'), table_name='connector_configs')
    op.drop_table('connector_configs')
    op.drop_index(op.f('ix_cbam_records_product_code'), table_name='cbam_records')
    op.drop_index(op.f('ix_cbam_records_organization_id'), table_name='cbam_records')
    op.drop_index(op.f('ix_cbam_records_is_deleted'), table_name='cbam_records')
    op.drop_table('cbam_records')
    op.drop_index(op.f('ix_baselines_organization_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_is_deleted'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_anomaly_records_organization_id'), table_name='anomaly_records')
    op.drop_index(op.f('ix_anomaly_records_is_deleted'), table_name='anomaly_records')
    op.drop_index(op.f('ix_anomaly_records_activity_data_id'), table_name='anomaly_records')
    op.drop_table('anomaly_records')
    op.drop_index(op.f('ix_allocations_organization_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_is_deleted'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_activity_data_scope'), table_name='activity_data')
    op.drop_index(op.f('ix_activity_data_organization_id'), table_name='activity_data')
    op.drop_index(op.f('ix_activity_data_is_deleted'), table_name='activity_data')
    op.drop_index(op.f('ix_activity_data_facility_id'), table_name='activity_data')
    op.drop_index(op.f('ix_activity_data_entity_id'), table_name='activity_data')
    op.drop_index(op.f('ix_activity_data_category'), table_name='activity_data')
    op.drop_index(op.f('ix_activity_data_anomaly_flag'), table_name='activity_data')
    op.drop_table('activity_data')
    # ### end Alembic commands ###
